[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.30"
auto_detect_solc = false
evm_version = "prague"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false
build_info = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read", path = "test/fixtures" }]

[invariant]
runs = 128
depth = 64
fail_on_revert = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
